version: '3.1'

services:

  back:
    container_name: "back"
    build:
      context: ./back
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on: # Wait for 'mysql' container to start before starting 'back'
      - mysql
    env_file:
      - ./back/.env
    networks: 
      - stack-net
    
  front:
    # image: front
    container_name: "front"
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./front/.env
    networks: 
      - stack-net

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306      
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_USER=admin
      - MYSQL_PASS=admin
      - MYSQL_DB=auth
    networks: 
      - stack-net
networks:
  stack-net:
    external: true